% ====================================================================== %
% Script for clinical data.
% Created on July, 2025
% Based on SWIFT version for ACS now for DoF RPL framework
% Description:
% BF Data (Acq in 2025 in Avendano CONTROL July 2025), reference Wisconsin*
% DOUBLE KIND OF ACQUISITION MONOFOCAL AND PLANEWAVE 
% (when load select % MONOFOC oR PW)

% Specific folder data: "bf_SavedDataCurvilinearPW"
% Reading BF data -> Spectral Data-> RFM & TNV-RFM
% Saves ROIs (previously generated by inspection)
% Saves MAPS DoFs
% ====================================================================== %

%%
init
warning('off')
%% WISCONSIN SPECS

% n_wisconsin = 3.76;
% b_wisonsin  = -54.81; % [dB]
alpha_ref   = 0.52; % [dB/cm/MHz]
sos_ref     = 1539; % [m/s]

n_wisconsin = 3.8;
n_healthy_lu = 1.4;
delta_n_lu  = n_healthy_lu - n_wisconsin; % delta_n_healthy = -2.4

b_wisonsin      = -55; % [dB]
b_healthy_lu    = -40; % [dB]
delta_b_lu  = b_healthy_lu - b_wisonsin; % delta_b_healthy = 27dB

% SUMARY (Lu et al)
% Healhty   : delta_n = -2.4, delta_b = 15dB
% Fat       : delta_n = -2.5, delta_b = 27dB
%%

% caseData = 'AS';
caseData = 'rest';

mean2d  = @(x) mean(x(:));
std2d   = @(x) std(x(:));
cv2d    = @(x) 100*std(x(:))/mean(x(:));
calc2dStats     = {@(x) mean(x(:)), @(x) std(x(:)), @(x) 100*std(x(:))/mean(x(:))};

% % CASE PW MONOFOC
% % General directory
% baseDir     = 'D:\emirandaz\qus\data\liver\bf_SavedDataCurvilinearPW\';
% % Sample and Reference directories
% sampleDir   = fullfile(baseDir,caseData,'sam');
% refsDir     = fullfile(baseDir,caseData,'ref');
% resultsOut  = 'res_Control_RFM';
% figuresOut  = 'fig_Control_RFM';

% % CASE OLD AVENDAÑO
% baseDir     = 'D:\emirandaz\qus\data\liver\bf_M04_D02';
% sampleDir   = fullfile(baseDir,'');
% resultsOut  = 'res_fatOld_RFM';
% figuresOut  = 'fig_fatOld_RFM';

polFolder   = 'polarFig';

resultsDir  = fullfile(baseDir,resultsOut);
figsDir     = fullfile(baseDir,figuresOut);
figsPolDir  = fullfile(baseDir,figuresOut, polFolder);

if ~exist(resultsDir) mkdir(resultsDir); end
if ~exist(figsDir) mkdir(figsDir); end
if ~exist(figsPolDir) mkdir(figsPolDir); end

% ROI MANUAL 
roi_manual      = true;
% roisDir         = fullfile(baseDir,'roisControl_PW');
% if ~exist(roisDir) mkdir(roisDir); end

range_bmode     = [-60 0];
range_depth     = [0 13];
range_acs       = [0 1.2];
transparency    = 0.65;
Np2dB           = 20*log10(exp(1));
dB2Np           = 1/Np2dB;
fontSize        = 14;

plotBmode       = false;
plotSpectrum    = false;
plotPolar       = false;
plotRect        = true;
save_data       = false;

% Read sample files
sampleFiles = dir(fullfile(sampleDir,'*.mat'));

% Specific sample
% acqDir = dir(fullfile(sampleDir,'016-03.mat')); %65*ma
% acqDir = dir(fullfile(sampleDir,'007-05.mat')); %*ma
% acqDir = dir(fullfile(sampleDir,'014-01.mat')); %*ma
% acqDir = dir(fullfile(sampleDir,'016-06.mat')); %emz
% sampleFiles     = dir(fullfile(sampleDir,'020-05.mat')); %dv

%% SPECTRAL METHOD PARAMETERS

pars.P           = 512; % NFFT for 10wl is 256, 20wl 512
pars.bw          = [1.5 3.5]; % [MHz]
pars.overlap     = 0.8;
pars.blocksize   = 10; % wavelengths
pars.blocklines  = 8;
pars.window_type = 3; %  (1) Hanning, (2) Tuckey, (3) Hamming, (4) Tchebychev
pars.saran_layer = false;
pars.ratio_zx    = 1;

%% GENERAL REGULARIZATION SETTINGS


%%

for iFile = 1:length(sampleFiles)

%% Loading file and variables
% samName = "000345400_IHR_F1";
samName = sampleFiles(iFile).name(1:end-4);
% SAM     = load(fullfile(sampleDir,samName+".mat")).PW; % PW
% SAM     = load(fullfile(sampleDir,samName+".mat")).MONOFOC; % MONOF

SAM     = load(fullfile(sampleDir,samName+".mat")); % MONOF

% fprintf("Loading sample: %s \n", samName)
fprintf("Loading sample %d / %d: %s \n", iFile, length(sampleFiles), samName)

bmode_sam   = SAM.bMode;
SAM.x       = SAM.xr; % original in in mm °, so °
SAM.z       = SAM.zr;
r0          = SAM.r0;

caption = strrep(samName, '_', '-');

%% Selecting ROI
bmodeFull = SAM.bMode;

if roi_manual

    figure('Units','centimeters', 'Position',[5 5 15 15]),
    imagesc(SAM.x, SAM.z*1E2,bmode_sam,range_bmode);
    colormap gray; clim(range_bmode);
    hb2=colorbar; ylabel(hb2,'dB')
    xlabel('\bfAngle [°]'); ylabel('\bfDepth [cm]');
    title(caption)

    confirmation = '';
    while ~strcmp(confirmation,'Yes')
        rect = getrect;
        confirmation = questdlg('Sure?');
        if strcmp(confirmation,'Cancel')
            disp(rect)
            break
        end
    end
    close,

else
% rois already saved execute full code
load(fullfile(roisDir,samName+".mat"),'rect');
    
end

pars.x_roi     = [rect(1), rect(1)+rect(3)];      % [º]
pars.z_roi     = [rect(2), rect(2)+rect(4)]*1E-2; % [m]

%% PACKAGE DATA FOR SPECTRAL FUNCTIONS

% Reference Depth
blocksize_wv_r = 24;
pars_ref            = pars;
pars_ref.blocksize  = blocksize_wv_r;% Reference Depth

%% BMODE CHECK

if (plotBmode)
deadBand = 0.1e-2;
figure,
set(gcf, 'Units', 'pixels', 'Position', [50, 100, 1200, 600]); % [x, y, width, height]

subplot(121), 
imagesc(SAM.x, SAM.z*1E2, bmode_sam, range_bmode), 
% axis("image"), 
hold on;
rectangle('Position', [1, 1E2, 1, 1E2].*[pars.x_roi(1) pars.z_roi(1) pars.x_roi(2)-pars.x_roi(1) pars.z_roi(2)-pars.z_roi(1)], ...
        'EdgeColor','w', 'LineWidth', 2, 'LineStyle','--'), hold off;
clim(range_bmode)
cb = colorbar;
cb.Label.String = 'dB'; % Add the label "dB"
xlabel('Lateral [°]'), ylabel('Depth [cm]');
title(caption)
ylim([deadBand*1000 range_depth(2)])
colormap('gray')

subplot(122), 
imagesc(REF.x, REF.z*1E2, bmode_ref, range_bmode), 
% axis("image");
rectangle('Position',  [1, 1E2, 1, 1E2].*[pars.x_roi(1) pars.z_roi(1) pars.x_roi(2)-pars.x_roi(1) pars.z_roi(2)-pars.z_roi(1)], ...
        'EdgeColor','w', 'LineWidth', 2, 'LineStyle','--'), hold off;
clim(range_bmode)
cb = colorbar;
cb.Label.String = 'dB'; % Add the label "dB"
xlabel('Lateral [°]'), ylabel('Depth [cm]');
title('REF')
colormap('gray')
ylim([deadBand*1000 range_depth(2)])
end

%% %% POWER SPECTRA ESTIMATION

%%%%%%%%%%%%% SAM %%%%%%%%%%%%%
spectralData_sam = calc_powerSpectraFull_vRFM(SAM, pars);
z_ACS            = spectralData_sam.depth;

% RFM
[m,  n, p]          = size(spectralData_sam.Sfull);
RSp_k               = zeros(m,n,p);
RSp_k(:,:, 2:end)   = spectralData_sam.Sfull(:,:, 2:end) ./ spectralData_sam.Sfull(:,:, 1:end-1); 
RSp_k(:,:, 1)       = RSp_k(:,:, 2); % Assuming the first slice ratios are 1 as there is no "i-1"
RSp_k               = log(RSp_k); % @@

%%%%%%%%%%%%% REF %%%%%%%%%%%%%

spectralData_ref    = calc_powerSpectraFull_vRFM(SAM, pars_ref);
z_ACS_r             = spectralData_ref.depth;
% RFM
[m_r,n, p]          = size(spectralData_ref.Sfull);
RSp_r               = zeros(m_r,n,p);
RSp_r(:,:, 2:end)   = spectralData_ref.Sfull(:,:, 2:end) ./ spectralData_ref.Sfull(:,:, 1:end-1); 
RSp_r(:,:, 1)       = RSp_r(:,:, 2); % Assuming the first slice ratios are 1 as there is no "i-1"
RSp_r               = log(RSp_r); % @@

%% PLOT SPECTRUM BY DEPTH

ratio_dB    = -20;
ratio       = db2mag(ratio_dB);

Sfull       = spectralData_sam.Sfull; % POWER LAW 3DOF

[m,n,~]     = size(spectralData_sam.Sfull);

nLines      = 5;
lin_cen     = round(n / 2); 
lat_range   = max(1, lin_cen-fix(nLines/2)):min(n, lin_cen+fix(nLines/2)); 

S_2d        = squeeze(mean(spectralData_sam.Sfull(:, lat_range, :), 2)); % Mean over 2nd dim (lateral)
S_2d_dB     = pow2db(S_2d ./ max(S_2d, [], 2));

if plotSpectrum

figure;
set(gcf,'units','normalized','outerposition',[0 0.1 0.5 0.5]); box on;

subplot(1,2,1)
imagesc(spectralData_sam.bandFull, spectralData_sam.depth*1e3, S_2d_dB),
xline(pars.bw(1), 'w--', 'LineWidth', 2)
xline(pars.bw(2), 'w--', 'LineWidth', 2)
xlim([0 SAM.fs/2]*1e-6); % visualize only positive size
xlabel('Frequency [MHz]');
ylabel('Depth [mm]');
h2 = colorbar; 
ylabel(h2,'dB');
title('SAM Norm Power Spectrum by depth');

subplot(1,2,2)
plot(spectralData_sam.bandFull, S_2d_dB(1, :), 'DisplayName', 'Top')
hold on, grid on;
plot(spectralData_sam.bandFull, S_2d_dB(round(m/2), :), 'DisplayName', 'Half')
plot(spectralData_sam.bandFull, S_2d_dB(end, :), 'DisplayName', 'Bottom')
yline(ratio_dB, 'k--', 'DisplayName', '')
xline(pars.bw(1), 'k--', 'DisplayName', '')
xline(pars.bw(2), 'k--', 'DisplayName', '')
xlim([0 SAM.fs/2]*1e-6); % visualize only positive size
hold off;
xlabel('Frequency [MHz]');
ylabel('Norm Power Spectrum [dB]');
title('SAM Norm Power Spectrum');
legend('Location', 'Best');

% exportgraphics(gcf,fullfile(figsDir,samName+"_powSp.png"), ...
%    'Resolution','300')
end


%% UFR strategy
bandFull    = spectralData_sam.bandFull;
bw_ufr      = pars.bw;
freqL       = bw_ufr(1); freqH = bw_ufr(2);
range       = bandFull >= freqL & bandFull <= freqH;

band_ufr    = bandFull(range);
p_ufr       = length(band_ufr);

RSp_k_ufr   = RSp_k(:,:,range);
RSp_r_ufr   = RSp_r(:,:,range);

%% TNV DENOISING

% DENOISING TNV RSP
mu          = 1.15;
tau         = 0.01000;
maxIter     = 1000;
stableIter  = 50;
% tol         = 0.5e-4; % tolerance error
tol         = 1e-3; % tolerance error
RSp_k_ufr_vec = reshape(RSp_k_ufr, [], size(RSp_k_ufr, 3));   
mux_RSp = 1./(abs(mean(RSp_k_ufr_vec, 1, 'omitnan')) ./ std(RSp_k_ufr_vec, 0, 1, 'omitnan') + 1E-5);
% weigthChannels = rescale(mux_RSp, 1, 10);
% weigthChannels = mux_RSp;
weigthChannels = ones(1, p_ufr);
 
% gamma = 1;
% vec_gamma = 1 + (1.1- 1) * (1 - linspace(0, 1, p_ufr).^gamma);
% vec_log = logspace(log10(10), log10(1), p_ufr);
% figure, plot(vec_gamma)
% 
% weigthChannels = vec_gamma;

[RSp_k_ufr_opt, cost, error, fid, reg] = pdo_den_wtnv(RSp_k_ufr, mu, tau, maxIter, tol, stableIter, weigthChannels);

[RSp_r_ufr_opt, cost, error, fid, reg] = pdo_den_wtnv(RSp_r_ufr, mu, tau, maxIter, tol, stableIter, weigthChannels);


% Convert depth values to cm
z_ACS_cm = z_ACS * 1e2;      % Convert from meters to cm
z_ACS_r_cm = z_ACS_r * 1e2;  % Convert reference depths to cm

% Delta MHz 
df_MHz = band_ufr(2) - band_ufr(1);

% Preallocate cell arrays for storing x_temp and y_temp
x_temp_all = cell(m, n);
y_temp_all = cell(m, n);
y_temp_all2 = cell(m, n);

tic;
for jj = 1:n  % Loop over lateral positions (x_j)
    for ii = 1:m  % Loop over depth positions (z_k)

        % Temporary storage for this location
        y_temp = nan(m_r, p_ufr);  % (Reference depth, Frequency) ** m_r
        y_temp2 = nan(m_r, p_ufr);  % (Reference depth, Frequency) ** m_r
        x_temp = nan(m_r, p_ufr);  % (Reference depth, Frequency) ** m_r

        for r = 1:m_r  % Loop over reference depths
            % if (ii==1 && r==1)
            y_col = squeeze( ( (RSp_k_ufr(ii, jj, :)) - (RSp_r_ufr(r, jj, :)) ) /(4*df_MHz) *Np2dB ); % p_ufr x 1
            y_col2 = squeeze( ( (RSp_k_ufr_opt(ii, jj, :)) - (RSp_r_ufr_opt(r, jj, :)) ) /(4*df_MHz) *Np2dB ); % p_ufr x 1
            
            X = z_ACS_cm(ii) - z_ACS_r_cm(r);

            y_temp(r, :) = y_col; %**
            y_temp2(r, :) = y_col2;
            x_temp(r, :) = X; % **

        end
        x_temp_all{ii, jj} = x_temp;
        y_temp_all{ii, jj} = y_temp;
        y_temp_all2{ii, jj} = y_temp2;

    end
end
t = toc;
fprintf('Loop way Elapsed time %.2f \n', t);
%%%%%%%%%%%%%%%%%%%% FAST WAY %%%%%%%%%%%%%%%%%%%%

% NOW ESTIMATION CGS RFM

a_rfm       = zeros(m, n); 
a_rfm_tnv   = zeros(m, n); 

for jj = 1:n  % Loop over lateral positions (x_j)
    for ii = 1:m  % Loop over depth positions (z_k)

        x_temp = x_temp_all{ii, jj};
        y_temp = y_temp_all{ii, jj};
        y_temp2 = y_temp_all2{ii, jj};

        X_vec = x_temp(:);
        y_vec = y_temp(:);
        y_vec2 = y_temp2(:);

        % % Option 1
        a_rfm(ii, jj) = -(X_vec' * X_vec) \ (X_vec' * y_vec);
        % a_rfm(ii, jj) = abs((X_vec' * X_vec) \ (X_vec' * y_vec));
        % 
        a_rfm_tnv(ii, jj) = -(X_vec' * X_vec) \ (X_vec' * y_vec2);
        % a_rfm_tnv(ii, jj) = abs((X_vec' * X_vec) \ (X_vec' * y_vec2));


        % % Option 2
        % A2_full    = kron(speye(p_ufr), x_temp(:, 1));
        % A2t_full   = A2_full';
        % 
        % slope_full = -(cgs(A2t_full*A2_full, A2t_full*y_vec));
        % slope2_full = -(cgs(A2t_full*A2_full, A2t_full*y_vec2));
        % 
        % a_rfm(ii, jj) = mean(slope_full);
        % a_rfm_tnv(ii, jj) = mean(slope2_full);

        % a_rfm(ii, jj) = median(slope_full);
        % a_rfm_tnv(ii, jj) = median(slope2_full);

        % % Option 3 (INTERCEPT)

        % A31_full   = kron( speye(p_ufr), x_temp(:, 1) );
        % A32_full   = kron( speye(p_ufr), ones(size( x_temp(:, 1))) );
        % A3_full    = horzcat(A31_full, A32_full);
        % A3t_full   = A3_full';
        % 
        % x_opt = -cgs(A3t_full*A3_full, A3t_full*y_vec);
        % slope_full = x_opt(1:end/2);
        % 
        % x2_opt = -cgs(A3t_full*A3_full, A3t_full*y_vec2);
        % slope2_full = x2_opt(1:end/2);
        % 
        % a_rfm(ii, jj) = mean(slope_full);
        % a_rfm_tnv(ii, jj) = mean(slope2_full);
        % 
        % % a_rfm(ii, jj) = median(slope_full);
        % % a_rfm_tnv(ii, jj) = median(slope2_full);


        % % Option 4 (LINEAR FIT)
        % slope_fit_fx = zeros(1, p_ufr);
        % slope_fit_fx2 = zeros(1, p_ufr);
        % for pp = 1:p_ufr
        %     [slope_fx, ~, ~, ~] = fit_linear(x_temp(:, pp), y_temp(:, pp), 2);
        %     [slope_fx2, ~, ~, ~] = fit_linear(x_temp(:, pp), y_temp2(:, pp), 2);
        %     slope_fit_fx(1,pp) =    -(slope_fx) ;
        %     slope_fit_fx2(1,pp) =   -(slope_fx2) ;
        % end
        % a_rfm(ii, jj) = mean(slope_fit_fx);
        % a_rfm_tnv(ii, jj) = mean(slope_fit_fx2);
        % 
        % % a_rfm(ii, jj) = median(slope_fit_fx);
        % % a_rfm_tnv(ii, jj) = median(slope_fit_fx2);


    end
end

%%


%% DOF METHODS


[m_a, s_a, cv_a]    = deal(calc2dStats{1}(a_rfm), calc2dStats{2}(a_rfm), calc2dStats{3}(a_rfm));
[m_a2, s_a2, cv_a2] = deal(calc2dStats{1}(a_rfm_tnv), calc2dStats{2}(a_rfm_tnv), calc2dStats{3}(a_rfm_tnv));


fprintf('-----RFM---\n');
fprintf('α_s        : %.4f ± %.4f, %%CV = %.4f\n', round(m_a, 3), round(s_a, 4), round(cv_a, 4));


fprintf('-----TNV-RFM---\n');
fprintf('α_s        : %.4f ± %.4f, %%CV = %.4f\n', round(m_a2, 3), round(s_a2, 4), round(cv_a2, 4));

maps_results_acs{1}.alpha = a_rfm;
maps_results_acs{2}.alpha = a_rfm_tnv;


methods      = {'RFM', 'TNV-RFM'};
method_labels = { ...
    '\mathrm{RFM}', ...
    '\mathrm{TNV\textrm{-}RFM}', ...
};
%% DISPLAY OVERLAY SIMPLE RECT
if plotRect

units           = 1E2;
bmodeFull       = bmode_sam;
% colorImg        = bigImg(acs_sam, spectralData_sam.rf_roi);
range_bmode     = [-60 0];
x_img           = spectralData_sam.lateral;
z_img           = spectralData_sam.depth*units;
xFull           = SAM.x;
zFull           = SAM.z*units;

[X,Z]   = meshgrid(xFull,zFull);
roi     = X >= x_img(1) & X <= x_img(end) & Z >= z_img(1) & Z <= z_img(end);

% %%%%%%%%%%%%%%%%%%%%%%% alpha %%%%%%%%%%%%%%%%%%%%%%%%
indices_alpha = [1, 2];  % Corresponden a RFM and TNV-RFM

figure('Units','pixels', 'Position',[50, 100, 1500, 500]) % [x, y, width, height]
tiledlayout(1,3, 'TileSpacing','compact', 'Padding','compact')

% Bmode
t1 = nexttile();
imagesc(xFull,zFull,bmodeFull,range_bmode); % axis image;
title(caption)
ylim(range_depth)
hold on
contour(xFull,zFull,roi,1,'w--')
hold off
xlabel('Lateral [°]')
ylabel('Depth [cm]')
hBm = colorbar('Ticks',-60:20:0);
% hBm = colorbar;
hBm.Label.String = 'dB';
hBm.Location = 'westoutside';
set(gca, 'fontsize', fontSize);

% RFM

% alpha maps
for i = 1:length(indices_alpha)
    idx = indices_alpha(i);
    nexttile;
    [~,~,hColor] = imOverlayInterp(bmodeFull, maps_results_acs{idx}.alpha, range_bmode, range_acs, ...
                                   transparency, x_img, z_img, roi, xFull, zFull);
    axis normal;
    hold on;
    contour(xFull, zFull, roi, 2, 'w--')
    hold off;
    ylim(range_depth)
    xlabel('Lateral [°]'), 
    % ylabel('Depth [cm]');
   
    hColor.Label.String = 'dB\cdotcm^{-1}\cdotMHz^{-1}';
    title(sprintf('$%s: \\alpha_s = %.2f \\pm %.2f, \\%%CV = %.2f$', ...
        method_labels{idx}, ...
        mean(maps_results_acs{idx}.alpha(:), 'omitnan'), ...
        std(maps_results_acs{idx}.alpha(:), 'omitnan'), ...
        abs(cv2d(maps_results_acs{idx}.alpha))), ...
        'Interpreter', 'latex');
    set(gca, 'fontsize', fontSize);
end
colormap(t1,'gray')
% exportgraphics(gcf,fullfile(figsDir,"sam_"+samName+"_a_rect.png"), ...
%    'Resolution','300')

end

%%  DISPLAY OVERLAY SIMPLE POLAR
if plotPolar

xPolar  = SAM.xp;
zPolar  = SAM.zp + 0.0101; % Trans.radiusMm*1e-3*(1-cos(phi(1)))
% zPolar  = SAM.zp;
z0Polar = SAM.z0p; 
r0      = SAM.r0;

parProbe = getparam('C5-2v');
[~,~,z0Polar2] = impolgrid(size(bmode_sam), SAM.z(end)+r0, parProbe);

% Plot in cartesian cords
[TH_acs,R_acs]          = meshgrid(-x_img*pi/180 + pi/2,z_img/100+r0);
[xPolarACS,zPolarACS]   = pol2cart(TH_acs,R_acs);
zPolarACS               = zPolarACS + z0Polar;

%%%%%%%%%%%%%%%%%%%%%%% BMODE %%%%%%%%%%%%%%%%%%%%%%%
figure('Units', 'pixels', 'Position', [50, 100, 400, 300]); % [x, y, width, height]
[ax1,~] = imOverlayPolar(bmodeFull,ones(size(maps_results_acs{1}.alpha)),range_bmode,range_acs,0, ...
    xPolar,zPolar,xPolarACS,zPolarACS);
% yticks(ax1,[4 8 12 16])
xlabel(ax1,'Lateral [cm]'), ylabel(ax1,'Axial [cm]')
title(ax1, samName, 'Interpreter', 'none');
xlim([-9 9])
ylim(range_depth)
hold on
contour(xPolar*1e2, zPolar*1e2, roi,1,'w--')
hold off
set(gca, 'fontsize', fontSize);
% exportgraphics(gcf,fullfile(figsPolDir,"sam_"+samName+"_pol"+num2str(idx)+".png"), ...
% 'Resolution','300')

%% QUS PARAMETERS

%%%%%%%%%%%%%%%%%%%%%%%% alpha %%%%%%%%%%%%%%%%%%%%%%%%

for i = 1:length(indices_alpha)
    figure('Units', 'pixels', 'Position', [50, 100, 400, 300]); % [x, y, width, height]
    idx = indices_alpha(i);

    % [ax1,~] = imOverlayPolar(bmodeFull,ones(size(maps_results_dof{1}.alpha)),range_bmode,range_acs,0, ...
    %     xPolar,zPolar,xPolarACS,zPolarACS);
    [ax1,~] = imOverlayPolar(bmodeFull,maps_results_acs{idx}.alpha,range_bmode,range_acs,transparency, ...
        xPolar,zPolar,xPolarACS,zPolarACS);
    % yticks(ax1,[4 8 12 16])
    xlabel(ax1,'Lateral [cm]'), ylabel(ax1,'Axial [cm]')

    title(ax1, sprintf('$%s: \\alpha_s = %.2f \\pm %.2f, \\%%CV = %.2f$', ...
        method_labels{idx}, ...
        mean(maps_results_acs{idx}.alpha(:), 'omitnan'), ...
        std(maps_results_acs{idx}.alpha(:), 'omitnan'), ...
        abs(cv2d(maps_results_acs{idx}.alpha))), ...
        'Interpreter', 'latex');

    xlim([-9 9])
    ylim(range_depth)
    hold on
    contour(xPolar*1e2, zPolar*1e2, roi,1,'w--')
    hold off
    % colorbar 
    % hColor.Label.String = 'dB\cdotcm^{-1}\cdotMHz^{-1}';
    set(gca, 'fontsize', fontSize);
    % exportgraphics(gcf,fullfile(figsPolDir,"sam_"+samName+"_a_pol"+num2str(idx)+".png"), ...
    % 'Resolution','300')
end

end

%% SAVING DATA
if save_data
    % Saving ACS maps and ROI
    save(fullfile(resultsDir,samName+".mat"), ...
        'maps_results_acs','rect')

    % first time working with roi
    save(fullfile(roisDir,samName+".mat"), ...
    'rect')

end

% close all
% pause (0.5);
keyboard
end
%% Auxiliary functions
% Get delays
function [t_delay] = getRXDelays(Trans, t, n_elements, n_pulses, sound_speed, wvl)

t_delay = zeros(length(t), n_elements, n_pulses);
% (x, z) [m] Obtain positions of center of every element
element_pos_x = Trans.ElementPos(:, 1)*wvl;
element_pos_z = Trans.ElementPos(:, 3)*wvl;
phi = Trans.ElementPos(:, 4);

for n = 1:n_pulses
    for e = 1:n_elements
        focus = sound_speed*t(:)/2;
        xfocus = element_pos_x(n) + sin(phi(n)) * focus;
        zfocus = element_pos_z(n) + cos(phi(n)) * focus;
        t_delay(:,e,n) = (focus + sqrt((zfocus- element_pos_z(e)).^2 + ...
            (xfocus - element_pos_x(e)).^2))/sound_speed;
    end
end

end